# hacemos el setup del proyecto

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[proyect]
name = "teoria"
version = "1.0.0"

[project.scripts]
teoriacomando = "teoria.__main__:main"